export const PHONE_DISPLAY = '(574) 564-9757'
export const PHONE_TEL = '+15745649757'
export const PHONE_SMS = '5745649757'
export const PHONE_WA = '15745649757'
export const BUSINESS = 'Gutierrez General Services LLC'

export const content = {
  en: {
    nav: { services: 'Services', area: 'Service area', contact: 'Get a quote', call: 'Call now', reviews: 'Reviews' },
    hero: {
      kicker: 'Warsaw, Indiana & surrounding areas',
      title: 'Professional detailing & cleaning services',
      sub: 'Detailing, paint correction, ceramic coating and heavy-duty cleaning for cars, trucks, SUVs, work vehicles, RVs, boats and heavy equipment.',
      cta1: 'Request a free quote',
      cta2: 'See services',
      cta3: 'Book now',
      bullets: ['Cars, trucks & SUVs', 'RVs & boats', 'Heavy equipment', 'Pressure washing'],
    },
    details: 'View details', close: 'Close',
    trust: [
      ['shield', 'Free Estimates'],
      ['check', 'Professional Service'],
      ['truck', 'Vehicles & Heavy Equipment'],
      ['pin', 'Warsaw, Indiana'],
    ],
    servicesTitle: 'Our services',
    servicesSub: 'Every job is done by hand, with professional products and attention to detail.',
    from: 'From',
    quote: 'Custom quote',
    freeQuote: 'Free quotes',
    priceNote: 'Price depends on size & condition',
    services: [
      {
        id: 'detailing', icon: 'car', title: 'Vehicle detailing', price: '$150', priceType: 'from',
        lead: 'Interior & exterior. A complete service to clean, refresh and improve the look of your vehicle.',
        items: ['Full vacuum', 'Deep carpet & upholstery cleaning', 'Dashboard, console & panel cleaning', 'Leather cleaning & conditioning', 'Interior surface protection', 'Hand exterior wash', 'Wheel & tire cleaning', 'Exterior trim & plastic cleaning', 'Drying & final finish'],
      },
      {
        id: 'polish', icon: 'sparkle', title: 'Polishing & paint correction', price: '$400', priceType: 'from',
        lead: 'Designed to restore gloss and improve the look of your paint.',
        items: ['Wash & paint decontamination', 'Clay bar treatment', 'Wet sanding where needed', 'Machine polishing', 'Swirl mark removal or reduction', 'Light scratch reduction', 'Oxidation removal', 'Paint correction & refinement', 'Final inspection'],
        note: 'Final price depends on vehicle size, paint condition and level of correction needed.',
      },
      {
        id: 'ceramic', icon: 'shield', title: 'Ceramic coating', price: '$700', priceType: 'from',
        lead: 'Long-lasting paint protection, applied after the necessary prep and correction.',
        items: ['Deep wash', 'Paint decontamination', 'Clay bar', 'Polishing & correction as needed', 'Surface preparation', 'Ceramic coating application', 'Inspection & final finish'],
        note: 'Different coating options available depending on the protection level and durability you want. Price depends on vehicle size, paint condition and product used.',
      },
      {
        id: 'trucks', icon: 'truck', title: 'SUVs, pickups & trucks', price: '$175', priceType: 'from',
        lead: 'Specialized services for larger vehicles.',
        items: ['Interior detailing', 'Exterior wash', 'Deep cleaning', 'Wheel & tire cleaning', 'Paint decontamination', 'Polishing', 'Paint correction', 'Paint protection', 'Interior protection'],
      },
      {
        id: 'rv', icon: 'rv', title: 'RVs & buses', price: null, priceType: 'quote',
        lead: 'Cleaning and detailing for recreational and oversized vehicles.',
        items: ['Exterior wash', 'Roof cleaning', 'Wheel & tire cleaning', 'Bug & road grime removal', 'Exterior decontamination', 'Exterior detailing', 'Interior cleaning', 'Degreasing', 'Finish & protection'],
        note: 'Priced by vehicle size and condition.',
      },
      {
        id: 'heavy', icon: 'tractor', title: 'Heavy equipment cleaning & degreasing', price: null, priceType: 'quote',
        lead: 'Specialized service for construction, agricultural and work machinery.',
        items: ['Pressure washing', 'Degreasing', 'Mud & dirt removal', 'Grease removal', 'Engine area cleaning', 'Chassis & undercarriage cleaning', 'General exterior cleaning'],
        note: 'Custom quote based on the equipment.',
      },
      {
        id: 'pressure', icon: 'water', title: 'Pressure washing', price: null, priceType: 'free',
        lead: 'Pressure washing for residential and commercial properties.',
        items: ['Driveways', 'Sidewalks', 'Patios', 'Concrete', 'Exterior walls', 'Other outdoor surfaces'],
        note: 'Free quotes.',
      },
    ],
    why: {
      title: 'Why choose us',
      items: [
        ['Hand-washed, never automated', 'Every vehicle is cleaned by hand with professional-grade products.'],
        ['From cars to heavy machinery', 'One team for your daily driver, your RV and your work equipment.'],
        ['Clear starting prices', 'You know the starting price before you call. Final quote based on size and condition.'],
        ['Local in Warsaw, IN', 'Serving Warsaw and nearby communities in Kosciusko County.'],
      ],
    },
    process: {
      title: 'How it works',
      steps: [
        ['Request your quote', 'Send us your info online or call us directly.'],
        ['We assess your vehicle or project', 'We review size, condition and the service you need.'],
        ['We schedule your service', 'We agree on a date, time and location that works for you.'],
        ['You get professional results', 'Hand-detailed work, done right, every time.'],
      ],
    },
    about: {
      title: 'About us',
      text: 'Gutierrez General Services LLC provides reliable detailing, cleaning and exterior care services for personal, commercial and work vehicles in Warsaw, Indiana and nearby areas. We show up on time, treat every vehicle like our own, and give you a clear price before we start.',
    },
    gallery: {
      title: 'Our work',
      sub: "Real before & after results from completed jobs, added as we finish them. Filter by category to see the type of work you're interested in.",
      all: 'All',
      soon: 'Photos coming soon',
      before: 'Before', after: 'After',
      categories: ['Cars', 'Trucks', 'RVs', 'Heavy Equipment', 'Pressure Washing'],
    },
    testimonials: {
      title: 'What our customers say',
      sub: 'Real reviews from real customers.',
      empty: "We're just getting started collecting reviews here — check back soon.",
    },
    area: { title: 'Service area', text: 'Based in Warsaw, Indiana. We serve Warsaw and surrounding areas — contact us to confirm availability for your location.' },
    contact: {
      title: 'Request a quote',
      sub: 'Tell us what you need and we will get back to you with a price. Or just call.',
      name: 'Your name', phone: 'Phone', city: 'City / location', service: 'Service', vehicle: 'Vehicle / equipment (year, make, model)', date: 'Preferred date', message: 'Condition, description or anything else we should know?',
      select: 'Select a service', send: 'Send request', sending: 'Sending…',
      consent: 'I agree to be contacted about my quote request by phone, text or WhatsApp.',
      ok: 'Thank you! We received your request and will contact you shortly.',
      okWa: 'Prefer WhatsApp? Send us your request now for a faster reply.',
      waBtn: 'Send via WhatsApp',
      err: 'We could not send your request. Please call or text us at',
      or: 'or', call: 'Call', text: 'Text',
    },
    footer: { rights: 'All rights reserved.', made: 'Website by' },
  },
  es: {
    nav: { services: 'Servicios', area: 'Zona de servicio', contact: 'Cotizar', call: 'Llamar', reviews: 'Reseñas' },
    hero: {
      kicker: 'Warsaw, Indiana y áreas cercanas',
      title: 'Detallado profesional y servicios de limpieza',
      sub: 'Detallado, corrección de pintura, recubrimiento cerámico y limpieza pesada para automóviles, camionetas, SUV, vehículos de trabajo, RV, botes y maquinaria pesada.',
      cta1: 'Pide una cotización gratis',
      cta2: 'Ver servicios',
      cta3: 'Reservar ahora',
      bullets: ['Autos, camionetas y SUV', 'RV y botes', 'Maquinaria pesada', 'Lavado a presión'],
    },
    details: 'Ver detalles', close: 'Cerrar',
    trust: [
      ['shield', 'Cotizaciones gratuitas'],
      ['check', 'Servicio profesional'],
      ['truck', 'Vehículos y maquinaria pesada'],
      ['pin', 'Warsaw, Indiana'],
    ],
    servicesTitle: 'Nuestros servicios',
    servicesSub: 'Cada trabajo se hace a mano, con productos profesionales y atención al detalle.',
    from: 'Desde',
    quote: 'Cotización personalizada',
    freeQuote: 'Cotización gratuita',
    priceNote: 'El precio depende del tamaño y condición',
    services: [
      {
        id: 'detailing', icon: 'car', title: 'Detallado de vehículos', price: '$150', priceType: 'from',
        lead: 'Interior y exterior. Servicio completo para limpiar, renovar y mejorar la apariencia de su vehículo.',
        items: ['Aspirado completo', 'Limpieza profunda de alfombras y tapicería', 'Limpieza de tablero, consola y paneles', 'Limpieza y acondicionamiento de cuero', 'Protección de superficies interiores', 'Lavado exterior a mano', 'Limpieza de ruedas y neumáticos', 'Limpieza de molduras y plásticos exteriores', 'Secado y acabado final'],
      },
      {
        id: 'polish', icon: 'sparkle', title: 'Pulido y corrección de pintura', price: '$400', priceType: 'from',
        lead: 'Servicio diseñado para mejorar el brillo y la apariencia de la pintura.',
        items: ['Lavado y descontaminación de la pintura', 'Tratamiento con clay bar', 'Lijado húmedo en áreas que lo requieran', 'Pulido con máquina', 'Eliminación o reducción de marcas de remolino', 'Reducción de rayones superficiales', 'Eliminación de oxidación', 'Corrección y refinamiento de la pintura', 'Inspección final'],
        note: 'El precio final depende del tamaño del vehículo, condición de la pintura y nivel de corrección necesario.',
      },
      {
        id: 'ceramic', icon: 'shield', title: 'Recubrimiento cerámico', price: '$700', priceType: 'from',
        lead: 'Protección de larga duración para la pintura después de la preparación y corrección necesaria.',
        items: ['Lavado profundo', 'Descontaminación de pintura', 'Clay bar', 'Pulido y corrección según sea necesario', 'Preparación de la superficie', 'Aplicación del recubrimiento cerámico', 'Inspección y acabado final'],
        note: 'Disponemos de diferentes opciones de recubrimiento según el nivel de protección y duración deseada. El precio depende del tamaño del vehículo, condición de la pintura y producto utilizado.',
      },
      {
        id: 'trucks', icon: 'truck', title: 'SUV, camionetas y camiones', price: '$175', priceType: 'from',
        lead: 'Servicios especializados para vehículos de mayor tamaño.',
        items: ['Detallado interior', 'Lavado exterior', 'Limpieza profunda', 'Limpieza de ruedas y neumáticos', 'Descontaminación de pintura', 'Pulido', 'Corrección de pintura', 'Protección de pintura', 'Protección de interiores'],
      },
      {
        id: 'rv', icon: 'rv', title: 'RV y autobuses', price: null, priceType: 'quote',
        lead: 'Limpieza y detallado para vehículos recreativos y de gran tamaño.',
        items: ['Lavado exterior', 'Limpieza de techo', 'Limpieza de ruedas y neumáticos', 'Eliminación de insectos y suciedad de carretera', 'Descontaminación exterior', 'Detallado exterior', 'Limpieza interior', 'Desengrase', 'Acabado y protección'],
        note: 'Precio según tamaño y condición del vehículo.',
      },
      {
        id: 'heavy', icon: 'tractor', title: 'Limpieza y desengrase de maquinaria pesada', price: null, priceType: 'quote',
        lead: 'Servicio especializado para equipos de construcción, agrícolas y maquinaria de trabajo.',
        items: ['Lavado a presión', 'Desengrase', 'Eliminación de barro y suciedad', 'Eliminación de grasa', 'Limpieza de áreas del motor', 'Limpieza del chasis y parte inferior', 'Limpieza exterior general'],
        note: 'Cotización personalizada según el equipo.',
      },
      {
        id: 'pressure', icon: 'water', title: 'Lavado a presión', price: null, priceType: 'free',
        lead: 'Lavado a presión para propiedades residenciales y comerciales.',
        items: ['Entradas de vehículos', 'Aceras', 'Patios', 'Concreto', 'Paredes exteriores', 'Otras superficies exteriores'],
        note: 'Cotizaciones gratuitas.',
      },
    ],
    why: {
      title: 'Por qué elegirnos',
      items: [
        ['Lavado a mano, nunca automático', 'Cada vehículo se limpia a mano con productos de grado profesional.'],
        ['De autos a maquinaria pesada', 'Un solo equipo para su carro, su RV y sus equipos de trabajo.'],
        ['Precios claros desde el inicio', 'Sabe el precio base antes de llamar. Cotización final según tamaño y condición.'],
        ['Locales en Warsaw, IN', 'Atendemos Warsaw y comunidades cercanas en el condado de Kosciusko.'],
      ],
    },
    process: {
      title: 'Cómo funciona',
      steps: [
        ['Solicite su cotización', 'Envíenos sus datos en línea o llámenos directamente.'],
        ['Evaluamos su vehículo o proyecto', 'Revisamos tamaño, condición y el servicio que necesita.'],
        ['Agendamos su servicio', 'Acordamos fecha, hora y lugar que le convengan.'],
        ['Recibe resultados profesionales', 'Trabajo hecho a mano, bien hecho, siempre.'],
      ],
    },
    about: {
      title: 'Sobre nosotros',
      text: 'Gutierrez General Services LLC ofrece servicios confiables de detallado, limpieza y cuidado exterior para vehículos personales, comerciales y de trabajo en Warsaw, Indiana y áreas cercanas. Llegamos a tiempo, tratamos cada vehículo como propio y le damos un precio claro antes de empezar.',
    },
    gallery: {
      title: 'Nuestro trabajo',
      sub: 'Aquí agregamos fotos de trabajos reales a medida que los completamos. Filtre por categoría para ver el tipo de trabajo que le interesa.',
      all: 'Todos',
      soon: 'Foto próximamente',
      before: 'Antes', after: 'Después',
      categories: ['Autos', 'Camionetas', 'RV', 'Maquinaria pesada', 'Lavado a presión'],
    },
    testimonials: {
      title: 'Lo que dicen nuestros clientes',
      sub: 'Reseñas reales de clientes reales.',
      empty: 'Apenas estamos empezando a recolectar reseñas aquí — vuelve pronto.',
    },
    area: { title: 'Zona de servicio', text: 'Ubicados en Warsaw, Indiana. Atendemos Warsaw y áreas cercanas — contáctenos para confirmar disponibilidad en su ubicación.' },
    contact: {
      title: 'Solicite una cotización',
      sub: 'Cuéntenos qué necesita y le respondemos con un precio. O simplemente llámenos.',
      name: 'Su nombre', phone: 'Teléfono', city: 'Ciudad / ubicación', service: 'Servicio', vehicle: 'Vehículo / equipo (año, marca, modelo)', date: 'Fecha preferida', message: '¿Condición, descripción o algo más que debamos saber?',
      select: 'Seleccione un servicio', send: 'Enviar solicitud', sending: 'Enviando…',
      consent: 'Acepto que me contacten sobre mi cotización por teléfono, mensaje de texto o WhatsApp.',
      ok: '¡Gracias! Recibimos su solicitud y lo contactaremos pronto.',
      okWa: '¿Prefiere WhatsApp? Envíenos su solicitud ahora para una respuesta más rápida.',
      waBtn: 'Enviar por WhatsApp',
      err: 'No pudimos enviar su solicitud. Llámenos o escríbanos al',
      or: 'o', call: 'Llamar', text: 'Mensaje',
    },
    footer: { rights: 'Todos los derechos reservados.', made: 'Sitio web por' },
  },
}
