export const PHONE_DISPLAY = '(574) 564-9757'
export const PHONE_TEL = '+15745649757'
export const PHONE_SMS = '5745649757'
export const PHONE_WA = '15745649757'
export const BUSINESS = 'Gutierrez General Services LLC'

export const content = {
  en: {
    nav: { services: 'Services', ourWork: 'Our Work', seasonal: 'Seasonal Care', contact: 'Contact', quote: 'Get a Free Quote', call: 'Call now' },
    hero: {
      kicker: 'Cleaner spaces. Brighter days.',
      titleLines: ['Clean outside.', 'Feel good', 'coming home.'],
      sub: 'Exterior cleaning, seasonal care, and vehicle & equipment cleaning for a cleaner, brighter Warsaw, Indiana.',
      cta1: 'Get a Free Quote',
    },
    details: 'View details', close: 'Close',
    servicesEyebrow: 'Our services',
    servicesTitle: "Care for what's outside.",
    servicesSub: 'Property care, seasonal support, and vehicle & equipment cleaning — for a cleaner, brighter community.',
    from: 'From',
    quote: 'Custom quote',
    freeQuote: 'Free estimates',
    services: [
      {
        id: 'exterior', group: 'exterior', icon: 'water', title: 'Exterior cleaning', price: null, priceType: 'free',
        lead: 'House facades, patios, driveways and more. Professional pressure washing to keep your property looking its best.',
        items: ['Driveways', 'Sidewalks', 'Patios', 'Concrete', 'House facades & exterior walls', 'Other outdoor surfaces'],
        note: 'Free estimates. Final price depends on the size and condition of the area.',
      },
      {
        id: 'seasonal', group: 'seasonal', icon: 'leaf', title: 'Seasonal care', price: null, priceType: 'quote',
        lead: 'Leaf cleanup in the fall and snow removal in the winter. Reliable help to keep your property safe and looking great through every season.',
        items: ['Fall leaf cleanup & removal', 'Winter snow removal', 'Seasonal property upkeep'],
        note: 'Custom quote based on property size and season.',
      },
      {
        id: 'detailing', group: 'vehicle', icon: 'car', title: 'Vehicle detailing', price: '$150', priceType: 'from',
        lead: 'Interior & exterior. A complete service to clean, refresh and improve the look of your vehicle.',
        items: ['Full vacuum', 'Deep carpet & upholstery cleaning', 'Dashboard, console & panel cleaning', 'Leather cleaning & conditioning', 'Interior surface protection', 'Hand exterior wash', 'Wheel & tire cleaning', 'Exterior trim & plastic cleaning', 'Drying & final finish'],
      },
      {
        id: 'polish', group: 'vehicle', icon: 'sparkle', title: 'Polishing & paint correction', price: '$400', priceType: 'from',
        lead: 'Designed to restore gloss and improve the look of your paint.',
        items: ['Wash & paint decontamination', 'Clay bar treatment', 'Wet sanding where needed', 'Machine polishing', 'Swirl mark removal or reduction', 'Light scratch reduction', 'Oxidation removal', 'Paint correction & refinement', 'Final inspection'],
        note: 'Final price depends on vehicle size, paint condition and level of correction needed.',
      },
      {
        id: 'ceramic', group: 'vehicle', icon: 'shield', title: 'Ceramic coating', price: '$700', priceType: 'from',
        lead: 'Long-lasting paint protection, applied after the necessary prep and correction.',
        items: ['Deep wash', 'Paint decontamination', 'Clay bar', 'Polishing & correction as needed', 'Surface preparation', 'Ceramic coating application', 'Inspection & final finish'],
        note: 'Different coating options available depending on the protection level and durability you want. Price depends on vehicle size, paint condition and product used.',
      },
      {
        id: 'trucks', group: 'vehicle', icon: 'truck', title: 'SUVs, pickups & trucks', price: '$175', priceType: 'from',
        lead: 'Specialized services for larger vehicles.',
        items: ['Interior detailing', 'Exterior wash', 'Deep cleaning', 'Wheel & tire cleaning', 'Paint decontamination', 'Polishing', 'Paint correction', 'Paint protection', 'Interior protection'],
      },
      {
        id: 'rv', group: 'vehicle', icon: 'rv', title: 'RVs & buses', price: null, priceType: 'quote',
        lead: 'Cleaning and detailing for recreational and oversized vehicles.',
        items: ['Exterior wash', 'Roof cleaning', 'Wheel & tire cleaning', 'Bug & road grime removal', 'Exterior decontamination', 'Exterior detailing', 'Interior cleaning', 'Degreasing', 'Finish & protection'],
        note: 'Priced by vehicle size and condition.',
      },
      {
        id: 'heavy', group: 'vehicle', icon: 'tractor', title: 'Heavy equipment cleaning & degreasing', price: null, priceType: 'quote',
        lead: 'Specialized service for construction, agricultural and work machinery.',
        items: ['Pressure washing', 'Degreasing', 'Mud & dirt removal', 'Grease removal', 'Engine area cleaning', 'Chassis & undercarriage cleaning', 'General exterior cleaning'],
        note: 'Custom quote based on the equipment.',
      },
    ],
    groups: {
      exterior: { title: 'Exterior cleaning', lead: 'House facades, patios, driveways and more. Professional pressure washing to keep your property looking its best.' },
      seasonal: { title: 'Seasonal care', lead: 'Leaf cleanup in the fall and snow removal in the winter. Reliable help to keep your property safe and looking great through every season.' },
      vehicle: { title: 'Vehicle & equipment care', lead: 'Detailed cleaning for cars, trucks and commercial equipment. A clean look that works as hard as you do.' },
    },
    gallery: {
      eyebrow: 'Our work',
      title: 'Real jobs, real results.',
      sub: "Photos from completed jobs, added as we finish them. Filter by category to see the type of work you're interested in.",
      all: 'All',
      soon: 'Photos coming soon',
      before: 'Before', after: 'After',
      catExterior: 'Exterior', catSeasonal: 'Seasonal', catVehicle: 'Vehicle & equipment',
    },
    contact: {
      eyebrow: 'Get a free quote',
      title: "Let's take care of your next project.",
      sub: "Tell us a little about what you need and we'll be in touch soon.",
      name: 'Name', phone: 'Phone', city: 'City / location', service: 'Type of service', vehicle: 'Vehicle / equipment (year, make, model)', date: 'Preferred date', message: 'Additional details (optional)',
      select: 'Select a service', send: 'Get a Free Quote', sending: 'Sending…',
      consent: 'I agree to be contacted about my quote request by phone, text or WhatsApp.',
      ok: 'Thank you! We received your request and will contact you shortly.',
      okWa: 'Prefer WhatsApp? Send us your request now for a faster reply.',
      waBtn: 'Send via WhatsApp',
      err: 'We could not send your request. Please call or text us at',
      or: 'or', call: 'Call', text: 'Text',
    },
    footer: { tagline: 'Clean spaces. Brighter days.', rights: 'All rights reserved.', made: 'Website by' },
  },
  es: {
    nav: { services: 'Servicios', ourWork: 'Nuestro trabajo', seasonal: 'Cuidado de temporada', contact: 'Contacto', quote: 'Cotización gratis', call: 'Llamar' },
    hero: {
      kicker: 'Espacios más limpios. Días más brillantes.',
      titleLines: ['Limpieza exterior.', 'Siéntase bien', 'al llegar a casa.'],
      sub: 'Limpieza exterior, cuidado de temporada y limpieza de vehículos y equipos para un Warsaw, Indiana más limpio y brillante.',
      cta1: 'Cotización gratis',
    },
    details: 'Ver detalles', close: 'Cerrar',
    servicesEyebrow: 'Nuestros servicios',
    servicesTitle: 'Cuidamos lo de afuera.',
    servicesSub: 'Cuidado de propiedades, apoyo de temporada y limpieza de vehículos y equipos — para una comunidad más limpia y brillante.',
    from: 'Desde',
    quote: 'Cotización personalizada',
    freeQuote: 'Cotizaciones gratuitas',
    services: [
      {
        id: 'exterior', group: 'exterior', icon: 'water', title: 'Limpieza exterior', price: null, priceType: 'free',
        lead: 'Fachadas, patios, entradas y más. Lavado a presión profesional para que su propiedad luzca lo mejor posible.',
        items: ['Entradas de vehículos', 'Aceras', 'Patios', 'Concreto', 'Fachadas y paredes exteriores', 'Otras superficies exteriores'],
        note: 'Cotizaciones gratuitas. El precio final depende del tamaño y condición del área.',
      },
      {
        id: 'seasonal', group: 'seasonal', icon: 'leaf', title: 'Cuidado de temporada', price: null, priceType: 'quote',
        lead: 'Recogida de hojas en otoño y retiro de nieve en invierno. Ayuda confiable para mantener su propiedad segura y en buen estado en cada temporada.',
        items: ['Recogida y retiro de hojas en otoño', 'Retiro de nieve en invierno', 'Mantenimiento de temporada'],
        note: 'Cotización personalizada según el tamaño de la propiedad y la temporada.',
      },
      {
        id: 'detailing', group: 'vehicle', icon: 'car', title: 'Detallado de vehículos', price: '$150', priceType: 'from',
        lead: 'Interior y exterior. Servicio completo para limpiar, renovar y mejorar la apariencia de su vehículo.',
        items: ['Aspirado completo', 'Limpieza profunda de alfombras y tapicería', 'Limpieza de tablero, consola y paneles', 'Limpieza y acondicionamiento de cuero', 'Protección de superficies interiores', 'Lavado exterior a mano', 'Limpieza de ruedas y neumáticos', 'Limpieza de molduras y plásticos exteriores', 'Secado y acabado final'],
      },
      {
        id: 'polish', group: 'vehicle', icon: 'sparkle', title: 'Pulido y corrección de pintura', price: '$400', priceType: 'from',
        lead: 'Servicio diseñado para mejorar el brillo y la apariencia de la pintura.',
        items: ['Lavado y descontaminación de la pintura', 'Tratamiento con clay bar', 'Lijado húmedo en áreas que lo requieran', 'Pulido con máquina', 'Eliminación o reducción de marcas de remolino', 'Reducción de rayones superficiales', 'Eliminación de oxidación', 'Corrección y refinamiento de la pintura', 'Inspección final'],
        note: 'El precio final depende del tamaño del vehículo, condición de la pintura y nivel de corrección necesario.',
      },
      {
        id: 'ceramic', group: 'vehicle', icon: 'shield', title: 'Recubrimiento cerámico', price: '$700', priceType: 'from',
        lead: 'Protección de larga duración para la pintura después de la preparación y corrección necesaria.',
        items: ['Lavado profundo', 'Descontaminación de pintura', 'Clay bar', 'Pulido y corrección según sea necesario', 'Preparación de la superficie', 'Aplicación del recubrimiento cerámico', 'Inspección y acabado final'],
        note: 'Disponemos de diferentes opciones de recubrimiento según el nivel de protección y duración deseada. El precio depende del tamaño del vehículo, condición de la pintura y producto utilizado.',
      },
      {
        id: 'trucks', group: 'vehicle', icon: 'truck', title: 'SUV, camionetas y camiones', price: '$175', priceType: 'from',
        lead: 'Servicios especializados para vehículos de mayor tamaño.',
        items: ['Detallado interior', 'Lavado exterior', 'Limpieza profunda', 'Limpieza de ruedas y neumáticos', 'Descontaminación de pintura', 'Pulido', 'Corrección de pintura', 'Protección de pintura', 'Protección de interiores'],
      },
      {
        id: 'rv', group: 'vehicle', icon: 'rv', title: 'RV y autobuses', price: null, priceType: 'quote',
        lead: 'Limpieza y detallado para vehículos recreativos y de gran tamaño.',
        items: ['Lavado exterior', 'Limpieza de techo', 'Limpieza de ruedas y neumáticos', 'Eliminación de insectos y suciedad de carretera', 'Descontaminación exterior', 'Detallado exterior', 'Limpieza interior', 'Desengrase', 'Acabado y protección'],
        note: 'Precio según tamaño y condición del vehículo.',
      },
      {
        id: 'heavy', group: 'vehicle', icon: 'tractor', title: 'Limpieza y desengrase de maquinaria pesada', price: null, priceType: 'quote',
        lead: 'Servicio especializado para equipos de construcción, agrícolas y maquinaria de trabajo.',
        items: ['Lavado a presión', 'Desengrase', 'Eliminación de barro y suciedad', 'Eliminación de grasa', 'Limpieza de áreas del motor', 'Limpieza del chasis y parte inferior', 'Limpieza exterior general'],
        note: 'Cotización personalizada según el equipo.',
      },
    ],
    groups: {
      exterior: { title: 'Limpieza exterior', lead: 'Fachadas, patios, entradas y más. Lavado a presión profesional para que su propiedad luzca lo mejor posible.' },
      seasonal: { title: 'Cuidado de temporada', lead: 'Recogida de hojas en otoño y retiro de nieve en invierno. Ayuda confiable para mantener su propiedad segura y en buen estado en cada temporada.' },
      vehicle: { title: 'Vehículos y equipos', lead: 'Limpieza detallada para autos, camiones y equipo comercial. Una imagen limpia que trabaja tan duro como usted.' },
    },
    gallery: {
      eyebrow: 'Nuestro trabajo',
      title: 'Trabajos reales, resultados reales.',
      sub: 'Fotos de trabajos completados, agregadas a medida que los terminamos. Filtre por categoría para ver el tipo de trabajo que le interesa.',
      all: 'Todos',
      soon: 'Fotos próximamente',
      before: 'Antes', after: 'Después',
      catExterior: 'Exterior', catSeasonal: 'Temporada', catVehicle: 'Vehículos y equipos',
    },
    contact: {
      eyebrow: 'Cotización gratis',
      title: 'Cuidemos su próximo proyecto.',
      sub: 'Cuéntenos un poco sobre lo que necesita y nos pondremos en contacto pronto.',
      name: 'Nombre', phone: 'Teléfono', city: 'Ciudad / ubicación', service: 'Tipo de servicio', vehicle: 'Vehículo / equipo (año, marca, modelo)', date: 'Fecha preferida', message: 'Detalles adicionales (opcional)',
      select: 'Seleccione un servicio', send: 'Cotización gratis', sending: 'Enviando…',
      consent: 'Acepto que me contacten sobre mi cotización por teléfono, mensaje de texto o WhatsApp.',
      ok: '¡Gracias! Recibimos su solicitud y lo contactaremos pronto.',
      okWa: '¿Prefiere WhatsApp? Envíenos su solicitud ahora para una respuesta más rápida.',
      waBtn: 'Enviar por WhatsApp',
      err: 'No pudimos enviar su solicitud. Llámenos o escríbanos al',
      or: 'o', call: 'Llamar', text: 'Mensaje',
    },
    footer: { tagline: 'Espacios limpios. Días más brillantes.', rights: 'Todos los derechos reservados.', made: 'Sitio web por' },
  },
}
