export const PHONE_DISPLAY = '(574) 564-9757'
export const PHONE_TEL = '+15745649757'
export const PHONE_SMS = '5745649757'
export const PHONE_WA = '15745649757'
export const BUSINESS = 'Gutierrez General Services LLC'

export const content = {
  en: {
    nav: { services: 'Services', plans: 'Plans', ourWork: 'Our Work', seasonal: 'Seasonal Care', contact: 'Contact', quote: 'Get a Free Quote', quoteShort: 'Get a Quote', call: 'Call now' },
    hero: {
      kicker: 'Local care · Warsaw, IN',
      titleLines: ['Your Car.', 'Your Home.', 'Taken Care Of.'],
      sub: 'Auto detailing, property care and seasonal services in Warsaw, Indiana.',
      cta1: 'Get a Free Quote',
      cta2: 'View Our Work',
    },
    details: 'View details', close: 'Close',
    servicesEyebrow: 'Our services',
    servicesTitle: 'One team for your car, your home, and every season.',
    servicesSub: 'Auto care, property care, and seasonal services — all from one trusted team.',
    from: 'From',
    quote: 'Custom quote',
    freeQuote: 'Free estimates',
    services: [
      {
        id: 'exterior', group: 'property', icon: 'water', title: 'Exterior cleaning', price: null, priceType: 'free',
        lead: 'House facades, patios, driveways and more. Professional pressure washing to keep your property looking its best.',
        items: ['Driveways', 'Sidewalks', 'Patios', 'Concrete', 'Gutter cleaning', 'House facades & exterior walls', 'Other outdoor surfaces'],
        note: 'Free estimates. Final price depends on the size and condition of the area.',
      },
      {
        id: 'seasonal', group: 'seasonal', icon: 'leaf', title: 'Seasonal care', price: null, priceType: 'quote',
        lead: 'Leaf cleanup in the fall and seasonal property upkeep. Reliable help to keep your property safe and looking great through every season.',
        items: ['Fall leaf cleanup & removal', 'Seasonal property upkeep'],
        note: 'Custom quote based on property size and season.',
      },
      {
        id: 'snow', group: 'seasonal', icon: 'snow', hidden: true, title: 'Snow removal', price: null, priceType: 'quote',
        lead: 'Manual and reliable snow and ice removal for driveways, walkways and entryways. Keeping your property safe and accessible all winter long.',
        items: ['Driveways', 'Walkways & sidewalks', 'Entryways & porches', 'Steps', 'Ice & salt treatment on request'],
        note: 'Custom quote based on property size and snowfall.',
      },
      {
        id: 'detailing', group: 'auto', icon: 'car', title: 'Vehicle detailing', price: '$150', priceType: 'from',
        lead: 'Interior & exterior. A complete service to clean, refresh and improve the look of your vehicle.',
        items: ['Full vacuum', 'Deep carpet & upholstery cleaning', 'Dashboard, console & panel cleaning', 'Leather cleaning & conditioning', 'Interior surface protection', 'Hand exterior wash', 'Wheel & tire cleaning', 'Exterior trim & plastic cleaning', 'Drying & final finish'],
      },
      {
        id: 'polish', group: 'auto', icon: 'sparkle', title: 'Polishing & paint correction', price: '$400', priceType: 'from',
        lead: 'Designed to restore gloss and improve the look of your paint.',
        items: ['Wash & paint decontamination', 'Clay bar treatment', 'Wet sanding where needed', 'Machine polishing', 'Swirl mark removal or reduction', 'Light scratch reduction', 'Oxidation removal', 'Paint correction & refinement', 'Final inspection'],
        note: 'Final price depends on vehicle size, paint condition and level of correction needed.',
      },
      {
        id: 'ceramic', group: 'auto', icon: 'shield', title: 'Ceramic coating', price: '$700', priceType: 'from',
        lead: 'Long-lasting paint protection, applied after the necessary prep and correction.',
        items: ['Deep wash', 'Paint decontamination', 'Clay bar', 'Polishing & correction as needed', 'Surface preparation', 'Ceramic coating application', 'Inspection & final finish'],
        note: 'Different coating options available depending on the protection level and durability you want. Price depends on vehicle size, paint condition and product used.',
      },
      {
        id: 'trucks', group: 'auto', icon: 'truck', title: 'SUVs, pickups & trucks', price: '$175', priceType: 'from',
        lead: 'Specialized services for larger vehicles.',
        items: ['Interior detailing', 'Exterior wash', 'Deep cleaning', 'Wheel & tire cleaning', 'Paint decontamination', 'Polishing', 'Paint correction', 'Paint protection', 'Interior protection'],
      },
      {
        id: 'rv', group: 'auto', icon: 'rv', title: 'RVs & buses', price: null, priceType: 'quote',
        lead: 'Cleaning and detailing for recreational and oversized vehicles.',
        items: ['Exterior wash', 'Roof cleaning', 'Wheel & tire cleaning', 'Bug & road grime removal', 'Exterior decontamination', 'Exterior detailing', 'Interior cleaning', 'Degreasing', 'Finish & protection'],
        note: 'Priced by vehicle size and condition.',
      },
      {
        id: 'heavy', group: 'auto', icon: 'tractor', title: 'Heavy equipment cleaning & degreasing', price: null, priceType: 'quote',
        lead: 'Specialized service for construction, agricultural and work machinery.',
        items: ['Pressure washing', 'Degreasing', 'Mud & dirt removal', 'Grease removal', 'Engine area cleaning', 'Chassis & undercarriage cleaning', 'General exterior cleaning'],
        note: 'Custom quote based on the equipment.',
      },
    ],
    groups: {
      auto: { title: 'Auto Care', lead: 'Interior and exterior detailing, polishing and protection for cars, trucks and equipment. A clean look that works as hard as you do.' },
      property: { title: 'Property Care', lead: 'House facades, patios, driveways, gutters and more. Professional pressure washing to keep your property looking its best.' },
      seasonal: { title: 'Seasonal Care', lead: 'Leaf cleanup and seasonal upkeep. Reliable help to keep your property safe and looking great through every season.' },
    },
    plans: {
      eyebrow: 'Membership',
      title: 'Monthly Care Plans',
      sub: 'Keep your vehicle and property maintained without scheduling every service separately.',
      priceFrom: 'Plans starting at $299/month',
      essential: { name: 'Essential Care', blurb: 'Regular care for your vehicle or your property.' },
      complete: { name: 'Complete Care', blurb: 'Combined care for both your vehicle and your property.' },
      cta: 'Ask About Monthly Plans',
      note: 'Save more with recurring service.',
    },
    howItWorks: {
      eyebrow: 'How it works',
      title: 'How It Works',
      steps: [
        { title: 'Tell Us What You Need', text: 'Choose vehicle care, property care, or both.' },
        { title: 'Get Your Quote', text: "Send us the details and we'll prepare your quote." },
        { title: 'We Take Care of It', text: "Schedule your service and we'll handle the rest." },
      ],
    },
    trust: {
      eyebrow: 'Why choose us',
      title: 'Why Customers Choose Us',
      points: [
        { icon: 'pin', title: 'Local & Dependable', text: 'Based right here in Warsaw, showing up when we say we will.' },
        { icon: 'hand', title: 'Personalized Service', text: 'We tailor every visit to your vehicle and your property.' },
        { icon: 'layers', title: 'Flexible Scheduling', text: 'Appointments that work around your life.' },
        { icon: 'home', title: 'One Contact for Home & Vehicle Care', text: 'A single trusted team for everything outside your door.' },
      ],
    },
    finalCta: {
      title: 'One Less Thing to Worry About.',
      text: 'Let us take care of your vehicle and property.',
      cta: 'Get a Free Quote',
    },
    gallery: {
      eyebrow: 'Our work',
      title: 'Real jobs, real results.',
      sub: "Photos from completed jobs.",
      all: 'All',
      before: 'Before', after: 'After',
      catExterior: 'Exterior', catSeasonal: 'Seasonal', catVehicle: 'Vehicle & equipment',
    },
    contact: {
      eyebrow: 'Get a free quote',
      title: 'Tell us what you need.',
      sub: "Share a few details about your service and we'll be in touch to prepare your quote.",
      typeLabel: 'What do you need help with?', typeVehicle: 'Vehicle', typeHome: 'Home', typeBoth: 'Both',
      name: 'Name', phone: 'Phone', email: 'Email (optional)', zip: 'ZIP / Address', service: 'Type of service', vehicle: 'Vehicle / equipment (year, make, model)', message: 'Additional details (optional)',
      photosNote: 'Have photos? You can text or WhatsApp them to us after submitting.',
      select: 'Select a service', send: 'Get My Quote', sending: 'Sending…',
      consent: 'I agree to be contacted about my quote request by phone, text or WhatsApp.',
      ok: 'Thank you! We received your request and will contact you shortly.',
      okWa: 'Prefer WhatsApp? Send us your request now for a faster reply.',
      waBtn: 'Send via WhatsApp',
      err: 'We could not send your request. Please call or text us at',
      or: 'or', call: 'Call', text: 'Text',
    },
    footer: { tagline: 'Clean spaces. Brighter days.', rights: 'All rights reserved.', made: 'Website by' },
    feedback: { title: 'Suggestions', placeholder: 'Write a suggestion…', empty: 'No suggestions yet.' },
  },
  es: {
    nav: { services: 'Servicios', plans: 'Planes', ourWork: 'Nuestro trabajo', seasonal: 'Cuidado de temporada', contact: 'Contacto', quote: 'Cotización gratis', quoteShort: 'Cotizar', call: 'Llamar' },
    hero: {
      kicker: 'Cuidado local · Warsaw, IN',
      titleLines: ['Su carro.', 'Su casa.', 'Bien cuidados.'],
      sub: 'Detallado de vehículos, cuidado de propiedades y servicios de temporada en Warsaw, Indiana.',
      cta1: 'Cotización gratis',
      cta2: 'Ver nuestro trabajo',
    },
    details: 'Ver detalles', close: 'Cerrar',
    servicesEyebrow: 'Nuestros servicios',
    servicesTitle: 'Un solo equipo para su carro, su casa y cada temporada.',
    servicesSub: 'Cuidado automotriz, de propiedades y servicios de temporada — todo con un equipo de confianza.',
    from: 'Desde',
    quote: 'Cotización personalizada',
    freeQuote: 'Cotizaciones gratuitas',
    services: [
      {
        id: 'exterior', group: 'property', icon: 'water', title: 'Limpieza exterior', price: null, priceType: 'free',
        lead: 'Fachadas, patios, entradas y más. Lavado a presión profesional para que su propiedad luzca lo mejor posible.',
        items: ['Entradas de vehículos', 'Aceras', 'Patios', 'Concreto', 'Limpieza de canaletas', 'Fachadas y paredes exteriores', 'Otras superficies exteriores'],
        note: 'Cotizaciones gratuitas. El precio final depende del tamaño y condición del área.',
      },
      {
        id: 'seasonal', group: 'seasonal', icon: 'leaf', title: 'Cuidado de temporada', price: null, priceType: 'quote',
        lead: 'Recogida de hojas en otoño y mantenimiento de temporada. Ayuda confiable para mantener su propiedad segura y en buen estado en cada temporada.',
        items: ['Recogida y retiro de hojas en otoño', 'Mantenimiento de temporada'],
        note: 'Cotización personalizada según el tamaño de la propiedad y la temporada.',
      },
      {
        id: 'snow', group: 'seasonal', icon: 'snow', hidden: true, title: 'Limpieza de nieve', price: null, priceType: 'quote',
        lead: 'Retiro manual y confiable de nieve y hielo en entradas, andenes y accesos. Mantenemos su propiedad segura y accesible durante todo el invierno.',
        items: ['Entradas de vehículos', 'Andenes y aceras', 'Accesos y porches', 'Escalones', 'Tratamiento de hielo y sal bajo solicitud'],
        note: 'Cotización personalizada según el tamaño de la propiedad y la nevada.',
      },
      {
        id: 'detailing', group: 'auto', icon: 'car', title: 'Detallado de vehículos', price: '$150', priceType: 'from',
        lead: 'Interior y exterior. Servicio completo para limpiar, renovar y mejorar la apariencia de su vehículo.',
        items: ['Aspirado completo', 'Limpieza profunda de alfombras y tapicería', 'Limpieza de tablero, consola y paneles', 'Limpieza y acondicionamiento de cuero', 'Protección de superficies interiores', 'Lavado exterior a mano', 'Limpieza de ruedas y neumáticos', 'Limpieza de molduras y plásticos exteriores', 'Secado y acabado final'],
      },
      {
        id: 'polish', group: 'auto', icon: 'sparkle', title: 'Pulido y corrección de pintura', price: '$400', priceType: 'from',
        lead: 'Servicio diseñado para mejorar el brillo y la apariencia de la pintura.',
        items: ['Lavado y descontaminación de la pintura', 'Tratamiento con clay bar', 'Lijado húmedo en áreas que lo requieran', 'Pulido con máquina', 'Eliminación o reducción de marcas de remolino', 'Reducción de rayones superficiales', 'Eliminación de oxidación', 'Corrección y refinamiento de la pintura', 'Inspección final'],
        note: 'El precio final depende del tamaño del vehículo, condición de la pintura y nivel de corrección necesario.',
      },
      {
        id: 'ceramic', group: 'auto', icon: 'shield', title: 'Recubrimiento cerámico', price: '$700', priceType: 'from',
        lead: 'Protección de larga duración para la pintura después de la preparación y corrección necesaria.',
        items: ['Lavado profundo', 'Descontaminación de pintura', 'Clay bar', 'Pulido y corrección según sea necesario', 'Preparación de la superficie', 'Aplicación del recubrimiento cerámico', 'Inspección y acabado final'],
        note: 'Disponemos de diferentes opciones de recubrimiento según el nivel de protección y duración deseada. El precio depende del tamaño del vehículo, condición de la pintura y producto utilizado.',
      },
      {
        id: 'trucks', group: 'auto', icon: 'truck', title: 'SUV, camionetas y camiones', price: '$175', priceType: 'from',
        lead: 'Servicios especializados para vehículos de mayor tamaño.',
        items: ['Detallado interior', 'Lavado exterior', 'Limpieza profunda', 'Limpieza de ruedas y neumáticos', 'Descontaminación de pintura', 'Pulido', 'Corrección de pintura', 'Protección de pintura', 'Protección de interiores'],
      },
      {
        id: 'rv', group: 'auto', icon: 'rv', title: 'RV y autobuses', price: null, priceType: 'quote',
        lead: 'Limpieza y detallado para vehículos recreativos y de gran tamaño.',
        items: ['Lavado exterior', 'Limpieza de techo', 'Limpieza de ruedas y neumáticos', 'Eliminación de insectos y suciedad de carretera', 'Descontaminación exterior', 'Detallado exterior', 'Limpieza interior', 'Desengrase', 'Acabado y protección'],
        note: 'Precio según tamaño y condición del vehículo.',
      },
      {
        id: 'heavy', group: 'auto', icon: 'tractor', title: 'Limpieza y desengrase de maquinaria pesada', price: null, priceType: 'quote',
        lead: 'Servicio especializado para equipos de construcción, agrícolas y maquinaria de trabajo.',
        items: ['Lavado a presión', 'Desengrase', 'Eliminación de barro y suciedad', 'Eliminación de grasa', 'Limpieza de áreas del motor', 'Limpieza del chasis y parte inferior', 'Limpieza exterior general'],
        note: 'Cotización personalizada según el equipo.',
      },
    ],
    groups: {
      auto: { title: 'Cuidado automotriz', lead: 'Detallado interior y exterior, pulido y protección para autos, camiones y equipo. Una imagen limpia que trabaja tan duro como usted.' },
      property: { title: 'Cuidado de propiedad', lead: 'Fachadas, patios, entradas, canaletas y más. Lavado a presión profesional para que su propiedad luzca lo mejor posible.' },
      seasonal: { title: 'Cuidado de temporada', lead: 'Recogida de hojas y mantenimiento de temporada. Ayuda confiable para mantener su propiedad segura y en buen estado en cada temporada.' },
    },
    plans: {
      eyebrow: 'Membresía',
      title: 'Planes mensuales de cuidado',
      sub: 'Mantenga su vehículo y su propiedad en buen estado sin programar cada servicio por separado.',
      priceFrom: 'Planes desde $299/mes',
      essential: { name: 'Cuidado Esencial', blurb: 'Cuidado regular para su vehículo o su propiedad.' },
      complete: { name: 'Cuidado Completo', blurb: 'Cuidado combinado para su vehículo y su propiedad.' },
      cta: 'Preguntar por planes mensuales',
      note: 'Ahorre más con servicio recurrente.',
    },
    howItWorks: {
      eyebrow: 'Cómo funciona',
      title: 'Cómo funciona',
      steps: [
        { title: 'Cuéntenos qué necesita', text: 'Elija cuidado de vehículo, de propiedad, o ambos.' },
        { title: 'Reciba su cotización', text: 'Envíenos los detalles y prepararemos su cotización.' },
        { title: 'Nosotros nos encargamos', text: 'Programe su servicio y nosotros hacemos el resto.' },
      ],
    },
    trust: {
      eyebrow: 'Por qué elegirnos',
      title: 'Por qué nuestros clientes nos eligen',
      points: [
        { icon: 'pin', title: 'Local y confiable', text: 'Con base aquí en Warsaw, cumplimos cuando decimos que lo haremos.' },
        { icon: 'hand', title: 'Servicio personalizado', text: 'Adaptamos cada visita a su vehículo y su propiedad.' },
        { icon: 'layers', title: 'Horarios flexibles', text: 'Citas que se ajustan a su día a día.' },
        { icon: 'home', title: 'Un solo contacto para casa y vehículo', text: 'Un equipo de confianza para todo lo de afuera de su puerta.' },
      ],
    },
    finalCta: {
      title: 'Una preocupación menos.',
      text: 'Déjenos cuidar su vehículo y su propiedad.',
      cta: 'Cotización gratis',
    },
    gallery: {
      eyebrow: 'Nuestro trabajo',
      title: 'Trabajos reales, resultados reales.',
      sub: 'Fotos de trabajos completados.',
      all: 'Todos',
      before: 'Antes', after: 'Después',
      catExterior: 'Exterior', catSeasonal: 'Temporada', catVehicle: 'Vehículos y equipos',
    },
    contact: {
      eyebrow: 'Cotización gratis',
      title: 'Cuéntenos qué necesita.',
      sub: 'Comparta algunos detalles de su servicio y nos pondremos en contacto para preparar su cotización.',
      typeLabel: '¿Con qué necesita ayuda?', typeVehicle: 'Vehículo', typeHome: 'Casa', typeBoth: 'Ambos',
      name: 'Nombre', phone: 'Teléfono', email: 'Correo (opcional)', zip: 'Código postal / Dirección', service: 'Tipo de servicio', vehicle: 'Vehículo / equipo (año, marca, modelo)', message: 'Detalles adicionales (opcional)',
      photosNote: '¿Tiene fotos? Puede enviarlas por mensaje de texto o WhatsApp después de enviar el formulario.',
      select: 'Seleccione un servicio', send: 'Obtener mi cotización', sending: 'Enviando…',
      consent: 'Acepto que me contacten sobre mi cotización por teléfono, mensaje de texto o WhatsApp.',
      ok: '¡Gracias! Recibimos su solicitud y lo contactaremos pronto.',
      okWa: '¿Prefiere WhatsApp? Envíenos su solicitud ahora para una respuesta más rápida.',
      waBtn: 'Enviar por WhatsApp',
      err: 'No pudimos enviar su solicitud. Llámenos o escríbanos al',
      or: 'o', call: 'Llamar', text: 'Mensaje',
    },
    footer: { tagline: 'Espacios limpios. Días más brillantes.', rights: 'Todos los derechos reservados.', made: 'Sitio web por' },
    feedback: { title: 'Sugerencias', placeholder: 'Escribe una sugerencia…', empty: 'No hay sugerencias todavía.' },
  },
}
